---

# This is the ssh user you use from the control machine to the target machine
ansible_user: root

# The deb to install
eos_deb: https://github.com/EOSIO/eos/releases/download/v1.7.4/eosio_1.7.4-1-ubuntu-18.04_amd64.deb

# A simple reference, it doesnt have to be a producer name
agent_name: add_your_name

# The user to create which will run nodeos
ops_user: eos

# Override the default install locations
mainnet_install_dir: /opt/mainnet

# Use these settings for non standard ssh port and/or ssh key
# ansible_ssh_private_key_file: ~/.ssh/key.pem
# ansible_port: 4567
